### ISSUE TITLE
Cursor is off when typing

### ISSUE THREAD

**Issue by nashio** [kwinyyyc/strapi-plugin-wysiwyg-react-md-editor#50]
I noticed that as I am typing cursor is off, and the offset becomes larger as you type more lines.
Almost as if the line-height of `<pre>` would be different to the `<textarea>`.

![Image](https://github.com/user-attachments/assets/762a4f96-4769-4cb0-beda-4df969bc3854)

version: `^5.8.2"`
tested: Chrome, Firefox, Brave

**Comment by tdjsnelling** [comment]
It looks like this is caused by Prism applying styles to `code[class*="language-"], pre[class*="language-"]`, which includes `.w-md-editor-text-pre`, overriding the line height.

I am working around this currently with a file `src/admin/custom.css`:

```css
.w-md-editor-content .w-md-editor-text-pre,
.w-md-editor-content .w-md-editor-text-input {
  line-height: 18px !important;
}
```

And `src/admin/app.js`:

```js
import './custom.css'
export default {}
```
